#include "WiFiHelpers.h"

const char* wifiStatusDescription(wl_status_t status) {
  switch (status) {
    case WL_NO_SHIELD:
      return "WL_NO_SHIELD";
    case WL_IDLE_STATUS:
      return "WL_IDLE_STATUS";
    case WL_NO_SSID_AVAIL:
      return "WL_NO_SSID_AVAIL";
    case WL_SCAN_COMPLETED:
      return "WL_SCAN_COMPLETED";
    case WL_CONNECTED:
      return "WL_CONNECTED";
    case WL_CONNECT_FAILED:
      return "WL_CONNECT_FAILED";
    case WL_CONNECTION_LOST:
      return "WL_CONNECTION_LOST";
    case WL_WRONG_PASSWORD:
      return "WL_WRONG_PASSWORD";
    case WL_DISCONNECTED:
      return "WL_DISCONNECTED";
    default:
      return "UNKNOWN";
  }
}

const char* wifiDisconnectReasonDescription(WiFiDisconnectReason reason) {
  switch (reason) {
    case WIFI_DISCONNECT_REASON_UNSPECIFIED:
      return "WIFI_DISCONNECT_REASON_UNSPECIFIED";
    case WIFI_DISCONNECT_REASON_AUTH_EXPIRE:
      return "WIFI_DISCONNECT_REASON_AUTH_EXPIRE";
    case WIFI_DISCONNECT_REASON_AUTH_LEAVE:
      return "WIFI_DISCONNECT_REASON_AUTH_LEAVE";
    case WIFI_DISCONNECT_REASON_ASSOC_EXPIRE:
      return "WIFI_DISCONNECT_REASON_ASSOC_EXPIRE";
    case WIFI_DISCONNECT_REASON_ASSOC_TOOMANY:
      return "WIFI_DISCONNECT_REASON_ASSOC_TOOMANY";
    case WIFI_DISCONNECT_REASON_NOT_AUTHED:
      return "WIFI_DISCONNECT_REASON_NOT_AUTHED";
    case WIFI_DISCONNECT_REASON_NOT_ASSOCED:
      return "WIFI_DISCONNECT_REASON_NOT_ASSOCED";
    case WIFI_DISCONNECT_REASON_ASSOC_LEAVE:
      return "WIFI_DISCONNECT_REASON_ASSOC_LEAVE";
    case WIFI_DISCONNECT_REASON_ASSOC_NOT_AUTHED:
      return "WIFI_DISCONNECT_REASON_ASSOC_NOT_AUTHED";
    case WIFI_DISCONNECT_REASON_DISASSOC_PWRCAP_BAD:
      return "WIFI_DISCONNECT_REASON_DISASSOC_PWRCAP_BAD";
    case WIFI_DISCONNECT_REASON_DISASSOC_SUPCHAN_BAD:
      return "WIFI_DISCONNECT_REASON_DISASSOC_SUPCHAN_BAD";
    case WIFI_DISCONNECT_REASON_IE_INVALID:
      return "WIFI_DISCONNECT_REASON_IE_INVALID";
    case WIFI_DISCONNECT_REASON_MIC_FAILURE:
      return "WIFI_DISCONNECT_REASON_MIC_FAILURE";
    case WIFI_DISCONNECT_REASON_4WAY_HANDSHAKE_TIMEOUT:
      return "WIFI_DISCONNECT_REASON_4WAY_HANDSHAKE_TIMEOUT";
    case WIFI_DISCONNECT_REASON_GROUP_KEY_UPDATE_TIMEOUT:
      return "WIFI_DISCONNECT_REASON_GROUP_KEY_UPDATE_TIMEOUT";
    case WIFI_DISCONNECT_REASON_IE_IN_4WAY_DIFFERS:
      return "WIFI_DISCONNECT_REASON_IE_IN_4WAY_DIFFERS";
    case WIFI_DISCONNECT_REASON_GROUP_CIPHER_INVALID:
      return "WIFI_DISCONNECT_REASON_GROUP_CIPHER_INVALID";
    case WIFI_DISCONNECT_REASON_PAIRWISE_CIPHER_INVALID:
      return "WIFI_DISCONNECT_REASON_PAIRWISE_CIPHER_INVALID";
    case WIFI_DISCONNECT_REASON_AKMP_INVALID:
      return "WIFI_DISCONNECT_REASON_AKMP_INVALID";
    case WIFI_DISCONNECT_REASON_UNSUPP_RSN_IE_VERSION:
      return "WIFI_DISCONNECT_REASON_UNSUPP_RSN_IE_VERSION";
    case WIFI_DISCONNECT_REASON_INVALID_RSN_IE_CAP:
      return "WIFI_DISCONNECT_REASON_INVALID_RSN_IE_CAP";
    case WIFI_DISCONNECT_REASON_802_1X_AUTH_FAILED:
      return "WIFI_DISCONNECT_REASON_802_1X_AUTH_FAILED";
    case WIFI_DISCONNECT_REASON_CIPHER_SUITE_REJECTED:
      return "WIFI_DISCONNECT_REASON_CIPHER_SUITE_REJECTED";
    case WIFI_DISCONNECT_REASON_BEACON_TIMEOUT:
      return "WIFI_DISCONNECT_REASON_BEACON_TIMEOUT";
    case WIFI_DISCONNECT_REASON_NO_AP_FOUND:
      return "WIFI_DISCONNECT_REASON_NO_AP_FOUND";
    case WIFI_DISCONNECT_REASON_AUTH_FAIL:
      return "WIFI_DISCONNECT_REASON_AUTH_FAIL";
    case WIFI_DISCONNECT_REASON_ASSOC_FAIL:
      return "WIFI_DISCONNECT_REASON_ASSOC_FAIL";
    case WIFI_DISCONNECT_REASON_HANDSHAKE_TIMEOUT:
      return "WIFI_DISCONNECT_REASON_HANDSHAKE_TIMEOUT";
    default:
      return "UNKNOWN";
  }
}